// default
import type { Metadata } from 'next';
import { Nunito } from 'next/font/google';
// internal
import Providers from './providers';
import './globals.css';

const nunito = Nunito({
  weight: ['300', '400', '500', '700', '800'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-nunito',
});

export const metadata: Metadata = {
  title: 'Wateen - Platform',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunito.variable} sans-serif`} style={{ overflow: 'hidden' }}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
